version: 2
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/51aad069a98b3e35c6d2
jobs:
  build:
    docker:
      - image: cryptogoth/node-circle-test:49c98b3
    steps:
      - checkout
      - run: . ~/.profile; lerna bootstrap; lerna run build; lerna run lint # build before lint for TS packages
      - run:
          command: . ~/.profile; node packages/server/scripts/fullServer.js 127.0.0.1 8545 8546 30303
          background: true
      - run:
          shell: /bin/sh
          command: |
            cd packages/client; yarn test
