version: 2
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/51aad069a98b3e35c6d2
jobs:
  build:
    docker:
      - image: cryptogoth/node-circle-test:49c98b3
    steps:
      - checkout
      - run: pwd && ls && yarn
      - run: yarn lint
      - run: cd web; yarn; yarn lint
      - run:
          command: . ~/.profile; node server/scripts/fullServer.js 127.0.0.1 8545 8546 30303
          background: true
      - run:
          shell: /bin/sh
          command: |
            yarn test
