version: 2
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/51aad069a98b3e35c6d2
jobs:
  build:
    docker:
      - image: cryptogoth/node-circle-test:663bbd5
    steps:
      - checkout
      - run: pwd && ls && yarn
      - run: cd web; yarn
      - run: yarn lint
      - run:
          command: . ~/.profile; node scripts/fullServer.js 127.0.0.1 8545 8546 30303
          background: true
      - run:
          shell: /bin/sh
          command: |
            sleep 3 && echo -ne "join zktransfer hello\ngoodbye" | node scripts/testClient.js capetown.arcology.nyc 8547 true
      - run:
          shell: /bin/sh
          command: |
             echo -ne "join zktransfer hello\ngoodbye" | node scripts/testClient.js localhost 8546
